spring:

  #  DB, JWT 관련 정보  (gitIgnore)
  config:
    import:
      - secret/datasource.yml
      - secret/jwt.yml

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 10
